---
# tasks file for ocp_setup_tasks
  - name: upgrade all packages
    yum:
       name: '*'
       state: latest

  - name: Install needed packages
    yum:
      name:
        - bind
        - bind-utils
        - haproxy
        - httpd
        - vim
        - bash-completion
        - libselinux-python
        - podman
        - nfs-utils
        - git
        - firewalld
        - NetworkManager
      state: present

  - name: Dowloading OC clients 
    get_url:
      url: "{{ ocp_client }}"
      dest: /usr/local/src/openshift-client-linux.tar.gz

  - name: Dowloading OpenShift Installer
    get_url:
      url: "{{ ocp_installer }}"
      dest: /usr/local/src/openshift-install-linux.tar.gz

  - name: Unarchiving OC clients
    unarchive:
      src: /usr/local/src/openshift-client-linux.tar.gz
      dest: /usr/local/bin
      remote_src: yes

  - name: Unarchiving OpenShift Installer
    unarchive:
      src: /usr/local/src/openshift-install-linux.tar.gz
      dest: /usr/local/bin
      remote_src: yes

  - name: Removing files that are not needed
    file:
      path: /usr/local/bin/README.md
      state: absent



  - name: Change file ownership, group and permissions
    file:
      path: /opt/ocp4
      state: directory


  - name: Write out install-config file
    command : ssh-keygen -q -t rsa -b 4096  -f /opt/ocp4/ocp4_rsa -C noname -N ""
    args:
       creates: /opt/ocp4/ocp4_rsa

  - name: create RSA KEY
    openssh_keypair:
      path: /opt/ocp4/ocp4_rsa
      force: True
      comment: "noname"
    register: ocp_rsa_key



  - name: slurp the pubkey for passing to other servers as authorized_key
    slurp:
      src: /opt/ocp4/ocp4_rsa.pub
    register: new_rsa_key
  
  

  - name: Write out install-config file
    template:
      src: "{{ role_path }}/templates/install-config.yaml.j2"
      dest: /opt/ocp4/install-config.yaml

  - name: copy install-config.yaml file for forensic
    copy:
      src: /opt/ocp4/install-config.yaml
      dest: /opt/ocp4/install-config.yaml.bak
      remote_src: yes

  - name: Run openshift-install command
    command: chdir=/opt/ocp4 openshift-install create ignition-configs --dir=/opt/ocp4


  - name: slurp the master ign for passing to other servers as authorized_key
    slurp:
      src: /opt/ocp4/master.ign
    register: master_ign


  - name: read master.ign 
    shell: cat "/opt/ocp4/master.ign"
    register: master_data
  
  - debug:
      msg: master_ign {{master_data}}
    
  - name: read worker.ign 
    shell: cat "/opt/ocp4/worker.ign"
    register: worker_data
  
  - debug:
      msg: master_ign {{worker_data}}


  - name: slurp the master ign for passing to other servers as authorized_key
    slurp:
      src: /opt/ocp4/worker.ign
    register: worker_ign
  
  - debug:
      msg: worker_ign

