---
# tasks file for update_vcenter

- name: Create Datacenter
  vmware_datacenter:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: '{{ datacenter_name }}'
    validate_certs: no
    state: present
  delegate_to: localhost

- name: Create Cluster
  vmware_cluster:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: '{{ datacenter_name }}'
    cluster_name: '{{ cluster_name }}'
    enable_ha: no
    enable_drs: yes
    enable_vsan: no
    validate_certs: no
  delegate_to: localhost

- name: Add ESXi Host to vCenter
  vmware_host:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ datacenter_name }}'
    cluster: '{{ cluster_name }}'
    esxi_hostname: '{{ target_esxi_ip }}'
    esxi_username: '{{ target_esxi_username }}'
    esxi_password: '{{ target_esxi_password}}'
    validate_certs: no
    state: present
  delegate_to: localhost

