---
# tasks file for upload_ocp_template




  - name: ansible create directory with mode setting  iso
    file:
      path: "{{tmp_space}}"
      state: directory
      mode: "u=rw,g=wx,o=rwx"

 

  - name: Check if ocp ova already fetched
    stat:
      path: "{{ tmp_space }}/{{ ocp_ova }}"
    register: ova_install

  - name: Download OCP4.2 installation ova file (might take a while)
    get_url:
      url: "{{ ocp_ova_url }}"
      dest: "{{ tmp_space }}/{{ ocp_ova }}"
      mode: 0440
    when: ova_install.stat.exists == False
    register: myovafile



  - name: Add resource pool to vCenter for uploading OVA template 
    vmware_resource_pool:
     hostname: '{{ vcenter_ip }}'
     username: '{{ vcenter_username }}'
     password: '{{ vcenter_password }}'
     datacenter: '{{ vcenter_datacenter }}'
     cluster: '{{ vcenter_cluster }}'
     resource_pool: ocp_ova_template_{{openshift_build}}
     mem_shares: normal
     mem_limit: -1
     mem_reservation: 0
     mem_expandable_reservations: yes
     cpu_shares: normal
     cpu_limit: -1
     cpu_reservation: 0
     cpu_expandable_reservations: yes
     validate_certs: no
     state: present
    delegate_to: localhost
   
   
  - name: Upload OCP OVA file  "{{ ocp_ova  }}"
    command: govc import.ova -name=rhcos-latest "{{ tmp_space }}/{{ ocp_ova }}"
    environment:
      GOVC_USERNAME: "{{ govc_username | default(ansible_env.GOVC_USERNAME) }}"
      GOVC_PASSWORD: "{{ govc_password | default(ansible_env.GOVC_PASSWORD) }}"
      GOVC_URL: "{{ govc_url | default(ansible_env.GOVC_URL) }}"
      GOVC_DATASTORE: "{{ govc_datastore | default(ansible_env.GOVC_DATASTORE) }}"
      GOVC_CLUSTER: "{{ govc_cluster | default(ansible_env.GOVC_CLUSTER) }}"
      GOVC_INSECURE: 1
      GOVC_RESOURCE_POOL: ocp_ova_template_{{openshift_build}}
  

  

  
