#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
# tasks file for vcsa-deploy

- name: Unmount the ISO
  mount:
    path: "{{ mount_dir_path }}"
    src: "{{ repo_dir }}/{{ vcsa_iso }}"
    fstype: iso9660
    state: unmounted
  tags:
    - cleanup

- name: Backup the embedded VCSA task file
  copy:
    src: "{{ vcsa_task_directory }}/deploy_embedded_appliance.yml"
    dest: "{{ vcsa_task_directory }}/deploy_embedded_appliance.yml.backup"
    backup: no
    mode: 0644
  when: appliance_type == "embedded"

- name: Backup the standalone VCSA task file
  copy:
    src: "{{ vcsa_task_directory }}/deploy_standalone_appliance.yml"
    dest: "{{ vcsa_task_directory }}/deploy_standalone_appliance.yml.backup"
    backup: no
    mode: 0644
  when: appliance_type == "standalone"

- name: Backup the PSC task file
  copy:
    src: "{{ vcsa_task_directory }}/deploy_psc_appliance.yml"
    dest: "{{ vcsa_task_directory }}/deploy_psc_appliance.yml.backup"
    backup: no
    mode: 0644
  when: appliance_type == "psc"

- name: Delete the embedded VCSA task file
  file:
    path: "{{ vcsa_task_directory }}/deploy_embedded_appliance.yml"
    state: absent
  when: appliance_type == "embedded"

- name: Delete the standalone VCSA task file
  file:
    path: "{{ vcsa_task_directory }}/deploy_standalone_appliance.yml"
    state: absent
  when: appliance_type == "standalone"

- name: Delete the PSC task file
  file:
    path: "{{ vcsa_task_directory }}/deploy_psc_appliance.yml"
    state: absent
  when: appliance_type == "psc"